os: osx
osx_image: xcode8
language: node_js
node_js:
- node
before_script:
  - npm install -g grunt-cli npm
after_script:
  - npm run publish-osx
env:
  global:
    secure: S6+zCDubz60catqjKteXlzU5VFeH5DNYFh9cAA8vlY8VQ7GNrCmHuU1Qt0i/bvmGhvSLl3xa36whm9zinMg94tvHXBwImNj1X0ibY2rm78s8DVsL9/UYB40uCmK+eq2epvUJfKEMmOLgKqlOqH+jQgSopzGUwBuBCXpuPKyHDfuAKQKCjrC0xTQh0GR9xskYjL+InFou/C6IwvCbIOtI6yE7O/C8A7ERzEbnk0N7kO/STQSsPPD/QSKfK5wAvE4wIrlvhKV+Z8Nor9N4Z55nOL3Q5iW9xsVALq4NW6hZ1SuCU26u2BrlxOVKTo1WD59BKR9H2ZeTeYoxoe71+UA08zxMlt2zCGyi2Xe1NoWbjb/0DtmPOCpFAr6TTlp820L2LaOimbNCJB7BBI8Utpqby/uXWyuUJPdFL1gnVKgcRNXiRSiltCZBORGjEPEFXKYiH81vuU8xPNIR4tmYjKCGAmzNVMLUeocxl6sMgvNGe1B53wqGnJVcGl9Ht5xJh4TDFQWzuWRDeCvO0oSzn+FhO2K2Kwb+jvDDOEJcprJxJBGnVznpRh8OENPPVbbblJa0F+OY95X9B3pJWKWI7hAOUCWnV9hXV5BSysQDfLjEsKC+nf2tU5cROhj/oraSykGerVDIcu8LivKAPeA0EcQZKcbgxuNDFUUJ7c7GtGES8Hw=
